name: tv-stfn
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch_geometric
  - rdkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - joblib
  - openpyxl
  - pip
  - pip:
    - xgboost
    - lightgbm
    - catboost
